# Generated by Django 3.2.15 on 2022-09-01 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0001_initial"),
    ]

    operations = []
